// app/layout.tsx
import type { Metadata } from "next";
import { Epilogue } from "next/font/google";
import "./globals.css";
import Nav from "./components/home/Nav";
import Footer from "./components/home/Footer";
import { TripProvider } from "./context/tripContext";


const epilogue = Epilogue({
  variable: "--font-epilogue",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "eCharter",
  description: "Generated by create next app",
  icons: {
    icon: "/bus.svg",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={` ${epilogue.variable} antialiased`}
      >
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.0/css/all.min.css"
          integrity="sha512-DxV+EoADOkOygM4IR9yXP8Sb2qwgidEmeqAEmDKIOfPRQZOWbXCzLC6vjbZyy0vPisbH2SyW27+ddLVCN+OMzQ=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
        <Nav />
        <TripProvider>
          {children}
        </TripProvider>
        <Footer />
      </body>
    </html>
  );
}
